
package vista;

// librerias especiales que permiten ejecutar la barra
import javax.swing.*; //interfaces graficas
import javax.swing.Timer;//manejo de tiempos hilos
import java.awt.Color;//colores en ventana
import java.awt.event.ActionEvent;//eventos
import java.awt.event.ActionListener;//escucha

public class OnlyLoad extends javax.swing.JFrame {

    private void ProgressBarIniciado() {//inicia metodo para cargar banner
    Timer mTimer = new Timer(45, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            pbCarga.setValue(pbCarga.getValue() + 1);
            pbCarga.setStringPainted(true);
           
            pbCarga.setString("Loading..." + pbCarga.getValue() + "%");

            // Detiene el temporizador cuando se llega al 100%
            if (pbCarga.getValue() >= 100) {
                pbCarga.setBackground(Color.BLUE);
                ((Timer)e.getSource()).stop();
               
                // Cierra la ventana de carga y abre la segunda ventana
                cerrarVentanaCarga();
                abrirNuevaVentana();
            }
        }
    });

    mTimer.start();//inicia objeto timer
}//termina banner
   
 // Método para cerrar la ventana de carga
private void cerrarVentanaCarga() {
    this.dispose(); // Cierra la ventana actual
}
    
// metodo para abrir una nueva ventana

private void abrirNuevaVentana () {
    Login ventanaLogin = new Login(); // instancia para abrir una ventana
    ventanaLogin.setVisible(true); // visualiza nueva ventana
}
    
    public OnlyLoad() {
        initComponents();
        this.setLocationRelativeTo(this);// centra ventana
        ProgressBarIniciado(); // llamada y ejecucion
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbCarga = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pbCarga.setBackground(new java.awt.Color(153, 0, 0));
        pbCarga.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pbCarga.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(pbCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 180, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Iniciando...");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoMontageCirculo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mar.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OnlyLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OnlyLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OnlyLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OnlyLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OnlyLoad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar pbCarga;
    // End of variables declaration//GEN-END:variables
}
